// Auto-generated by scripts/extract-step-definitions.ts
// Do not edit manually - run "bun run steps:extract" to regenerate

export interface StepDefinitionInfo {
  pattern: string;
  keyword: 'Given' | 'When' | 'Then';
  file: string;
  sourceCode: string;
  lineNumber: number;
}

export const stepDefinitions: StepDefinitionInfo[] = [
  {
    "pattern": "le portefeuille est vide",
    "keyword": "Given",
    "file": "connexion.steps.ts",
    "sourceCode": "Given('le portefeuille est vide', async function (this: FestipodWorld) {\n  // Verify starting state: the harness graph should have its own seeded data.\n  // We clear events/users/participations to simulate a truly empty wallet.\n  await this.appFrame!.evaluate(() => {\n    const td = (window as any).__testData;\n    // Delete all events\n    for (const e of [...td.events]) td.events.delete(e);\n    // Delete all users\n    for (const u of [...td.users]) td.users.delete(u);\n    // Delete all participations\n    for (const p of [...td.participations]) td.participations.delete(p);\n  });",
    "lineNumber": 10
  },
  {
    "pattern": "le portefeuille contient déjà des événements",
    "keyword": "Given",
    "file": "connexion.steps.ts",
    "sourceCode": "Given('le portefeuille contient déjà des événements', async function (this: FestipodWorld) {\n  const count = await this.appFrame!.evaluate(() => {\n    const td = (window as any).__testData;\n    return td.events.size;\n  });",
    "lineNumber": 32
  },
  {
    "pattern": "je charge les données de test",
    "keyword": "When",
    "file": "connexion.steps.ts",
    "sourceCode": "When('je charge les données de test', async function (this: FestipodWorld) {\n  // Store count before loading for the idempotency test\n  const countBefore = await this.appFrame!.evaluate(() => {\n    const td = (window as any).__testData;\n    return td.events.size;\n  });",
    "lineNumber": 53
  },
  {
    "pattern": "le portefeuille est connecté",
    "keyword": "Then",
    "file": "connexion.steps.ts",
    "sourceCode": "Then('le portefeuille est connecté', async function (this: FestipodWorld) {\n  const hasSession = await this.appFrame!.evaluate(() => {\n    const td = (window as any).__testData;\n    return td.session !== undefined && td.session !== null;\n  });",
    "lineNumber": 81
  },
  {
    "pattern": "le portefeuille ne contient aucun événement de démonstration",
    "keyword": "Then",
    "file": "connexion.steps.ts",
    "sourceCode": "Then('le portefeuille ne contient aucun événement de démonstration', async function (this: FestipodWorld) {\n  // Wallet should be empty — no auto-seeding.\n  // Also verify through the app's data context (same view as screens).\n  const result = await this.appFrame!.evaluate(() => {\n    const td = (window as any).__testData;\n    return {\n      walletEvents: td.events.size,\n      appEvents: td.appData?.events?.length ?? -1,\n      ngStatus: td.ngStatus,\n    };\n  });",
    "lineNumber": 89
  },
  {
    "pattern": "le portefeuille contient des événements",
    "keyword": "Then",
    "file": "connexion.steps.ts",
    "sourceCode": "Then('le portefeuille contient des événements', async function (this: FestipodWorld) {\n  const count = await this.appFrame!.evaluate(() => {\n    const td = (window as any).__testData;\n    return td.events.size;\n  });",
    "lineNumber": 106
  },
  {
    "pattern": "le portefeuille contient des utilisateurs",
    "keyword": "Then",
    "file": "connexion.steps.ts",
    "sourceCode": "Then('le portefeuille contient des utilisateurs', async function (this: FestipodWorld) {\n  const count = await this.appFrame!.evaluate(() => {\n    const td = (window as any).__testData;\n    return td.users.size;\n  });",
    "lineNumber": 114
  },
  {
    "pattern": "le nombre d'événements n'a pas changé",
    "keyword": "Then",
    "file": "connexion.steps.ts",
    "sourceCode": "Then('le nombre d\\'événements n\\'a pas changé', async function (this: FestipodWorld) {\n  const countBefore = (this as any)._eventCountBefore as number;\n  const countAfter = await this.appFrame!.evaluate(() => {\n    const td = (window as any).__testData;\n    return td.events.size;\n  });",
    "lineNumber": 122
  },
  {
    "pattern": "les événements ont des identifiants NextGraph",
    "keyword": "Then",
    "file": "connexion.steps.ts",
    "sourceCode": "Then('les événements ont des identifiants NextGraph', async function (this: FestipodWorld) {\n  const ids = await this.appFrame!.evaluate(() => {\n    const td = (window as any).__testData;\n    return [...td.events].map((e: any) => e['@id']);\n  });",
    "lineNumber": 131
  },
  {
    "pattern": "les utilisateurs ont des identifiants NextGraph",
    "keyword": "Then",
    "file": "connexion.steps.ts",
    "sourceCode": "Then('les utilisateurs ont des identifiants NextGraph', async function (this: FestipodWorld) {\n  const ids = await this.appFrame!.evaluate(() => {\n    const td = (window as any).__testData;\n    return [...td.users].map((u: any) => u['@id']);\n  });",
    "lineNumber": 142
  },
  {
    "pattern": "l'écran gère la redirection automatique après connexion",
    "keyword": "Then",
    "file": "connexion.steps.ts",
    "sourceCode": "Then('l\\'écran gère la redirection automatique après connexion', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  // LoginScreen must have a useEffect that navigates on status === 'connected'\n  const hasAutoNavigate =\n    source.includes('useEffect') &&\n    source.includes(\"status === 'connected'\") &&\n    source.includes(\"navigate\") &&\n    source.includes(\"'home'\");\n  expect(hasAutoNavigate, 'LoginScreen should auto-navigate to home when status becomes connected').to.be.true;\n});",
    "lineNumber": 5
  },
  {
    "pattern": "l'écran gère l'état de connexion en cours",
    "keyword": "Then",
    "file": "connexion.steps.ts",
    "sourceCode": "Then('l\\'écran gère l\\'état de connexion en cours', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  const hasConnectingState =\n    source.includes(\"status === 'connecting'\") ||\n    source.includes(\"Connexion NextGraph en cours\");\n  expect(hasConnectingState, 'LoginScreen should handle connecting state').to.be.true;\n});",
    "lineNumber": 16
  },
  {
    "pattern": "l'écran n'importe pas de données de démonstration",
    "keyword": "Then",
    "file": "connexion.steps.ts",
    "sourceCode": "Then('l\\'écran n\\'importe pas de données de démonstration', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  const importsSeedData = source.includes('seedData') || source.includes('seedEvents');\n  const usesFestipodData = source.includes('useFestipodData');\n  expect(importsSeedData, 'LoginScreen should not import seed data').to.be.false;\n  expect(usesFestipodData, 'LoginScreen should not use FestipodData context').to.be.false;\n});",
    "lineNumber": 24
  },
  {
    "pattern": "un événement {string} existe",
    "keyword": "Given",
    "file": "inscription.steps.ts",
    "sourceCode": "Given('un événement {string} existe', async function (this: FestipodWorld, eventTitle: string) {\n  const exists = await this.appFrame!.evaluate(\n    (title) => {\n      const td = (window as any).__testData;\n      return [...td.events].some((e: any) => e.title === title);\n    },\n    eventTitle,\n  );\n  expect(exists, `Event \"${eventTitle}\" should exist in the data layer`).to.be.true;\n});",
    "lineNumber": 10
  },
  {
    "pattern": "l'utilisateur n'est pas inscrit à l'événement {string}",
    "keyword": "Given",
    "file": "inscription.steps.ts",
    "sourceCode": "Given('l\\'utilisateur n\\'est pas inscrit à l\\'événement {string}', async function (this: FestipodWorld, eventTitle: string) {\n  await this.appFrame!.evaluate(\n    (title) => {\n      const td = (window as any).__testData;\n      const event = [...td.events].find((e: any) => e.title === title);\n      if (event) td.leaveEvent(event['@id'], td.currentUserId);\n    },\n    eventTitle,\n  );\n});",
    "lineNumber": 21
  },
  {
    "pattern": "l'utilisateur est inscrit à l'événement {string}",
    "keyword": "Given",
    "file": "inscription.steps.ts",
    "sourceCode": "Given('l\\'utilisateur est inscrit à l\\'événement {string}', async function (this: FestipodWorld, eventTitle: string) {\n  await this.appFrame!.evaluate(\n    (title) => {\n      const td = (window as any).__testData;\n      const event = [...td.events].find((e: any) => e.title === title);\n      if (event) td.joinEvent(event['@id'], td.currentUserId);\n    },\n    eventTitle,\n  );\n});",
    "lineNumber": 32
  },
  {
    "pattern": "l'événement {string} a {int} participants au départ",
    "keyword": "Given",
    "file": "inscription.steps.ts",
    "sourceCode": "Given('l\\'événement {string} a {int} participants au départ', async function (this: FestipodWorld, eventTitle: string, count: number) {\n  await this.appFrame!.evaluate(\n    ([title, c]: [string, number]) => {\n      const td = (window as any).__testData;\n      const event = [...td.events].find((e: any) => e.title === title);\n      if (event) td.updateEvent(event['@id'], { participantCount: c });",
    "lineNumber": 43
  },
  {
    "pattern": "l'utilisateur s'inscrit à l'événement {string}",
    "keyword": "When",
    "file": "inscription.steps.ts",
    "sourceCode": "When('l\\'utilisateur s\\'inscrit à l\\'événement {string}', async function (this: FestipodWorld, eventTitle: string) {\n  await this.appFrame!.evaluate(\n    (title) => {\n      const td = (window as any).__testData;\n      const event = [...td.events].find((e: any) => e.title === title);\n      if (event) td.joinEvent(event['@id'], td.currentUserId);\n    },\n    eventTitle,\n  );\n});",
    "lineNumber": 56
  },
  {
    "pattern": "l'utilisateur se désinscrit de l'événement {string}",
    "keyword": "When",
    "file": "inscription.steps.ts",
    "sourceCode": "When('l\\'utilisateur se désinscrit de l\\'événement {string}', async function (this: FestipodWorld, eventTitle: string) {\n  await this.appFrame!.evaluate(\n    (title) => {\n      const td = (window as any).__testData;\n      const event = [...td.events].find((e: any) => e.title === title);\n      if (event) td.leaveEvent(event['@id'], td.currentUserId);\n    },\n    eventTitle,\n  );\n});",
    "lineNumber": 67
  },
  {
    "pattern": "l'utilisateur essaie de s'inscrire une seconde fois à l'événement {string}",
    "keyword": "When",
    "file": "inscription.steps.ts",
    "sourceCode": "When('l\\'utilisateur essaie de s\\'inscrire une seconde fois à l\\'événement {string}', async function (this: FestipodWorld, eventTitle: string) {\n  await this.appFrame!.evaluate(\n    (title) => {\n      const td = (window as any).__testData;\n      const event = [...td.events].find((e: any) => e.title === title);\n      if (event) td.joinEvent(event['@id'], td.currentUserId);\n    },\n    eventTitle,\n  );\n});",
    "lineNumber": 78
  },
  {
    "pattern": "l'utilisateur est participant de l'événement {string}",
    "keyword": "Then",
    "file": "inscription.steps.ts",
    "sourceCode": "Then('l\\'utilisateur est participant de l\\'événement {string}', async function (this: FestipodWorld, eventTitle: string) {\n  const participating = await this.appFrame!.evaluate(\n    (title) => {\n      const td = (window as any).__testData;\n      const event = [...td.events].find((e: any) => e.title === title);\n      if (!event) return false;\n      return td.isParticipating(event['@id'], td.currentUserId);\n    },\n    eventTitle,\n  );\n  expect(participating, `User should be participating in \"${eventTitle}\"`).to.be.true;\n});",
    "lineNumber": 91
  },
  {
    "pattern": "l'utilisateur n'est plus participant de l'événement {string}",
    "keyword": "Then",
    "file": "inscription.steps.ts",
    "sourceCode": "Then('l\\'utilisateur n\\'est plus participant de l\\'événement {string}', async function (this: FestipodWorld, eventTitle: string) {\n  const participating = await this.appFrame!.evaluate(\n    (title) => {\n      const td = (window as any).__testData;\n      const event = [...td.events].find((e: any) => e.title === title);\n      if (!event) return false;\n      return td.isParticipating(event['@id'], td.currentUserId);\n    },\n    eventTitle,\n  );\n  expect(participating, `User should NOT be participating in \"${eventTitle}\"`).to.be.false;\n});",
    "lineNumber": 104
  },
  {
    "pattern": "l'événement {string} compte {int} participants",
    "keyword": "Then",
    "file": "inscription.steps.ts",
    "sourceCode": "Then('l\\'événement {string} compte {int} participants', async function (this: FestipodWorld, eventTitle: string, expectedCount: number) {\n  const count = await this.appFrame!.evaluate(\n    (title) => {\n      const td = (window as any).__testData;\n      const event = [...td.events].find((e: any) => e.title === title);\n      return event?.participantCount ?? -1;\n    },\n    eventTitle,\n  );\n  expect(count, `Event \"${eventTitle}\" participant count`).to.equal(expectedCount);\n});",
    "lineNumber": 117
  },
  {
    "pattern": "l'utilisateur apparaît dans la liste des participants de l'événement {string}",
    "keyword": "Then",
    "file": "inscription.steps.ts",
    "sourceCode": "Then('l\\'utilisateur apparaît dans la liste des participants de l\\'événement {string}', async function (this: FestipodWorld, eventTitle: string) {\n  const found = await this.appFrame!.evaluate(\n    (title) => {\n      const td = (window as any).__testData;\n      const event = [...td.events].find((e: any) => e.title === title);\n      if (!event) return false;\n      return td.getEventParticipants(event['@id']).some((p: any) => p.user === td.currentUserId);\n    },\n    eventTitle,\n  );\n  expect(found, `User should appear in participants of \"${eventTitle}\"`).to.be.true;\n});",
    "lineNumber": 129
  },
  {
    "pattern": "l'utilisateur n'apparaît plus dans la liste des participants de l'événement {string}",
    "keyword": "Then",
    "file": "inscription.steps.ts",
    "sourceCode": "Then('l\\'utilisateur n\\'apparaît plus dans la liste des participants de l\\'événement {string}', async function (this: FestipodWorld, eventTitle: string) {\n  const found = await this.appFrame!.evaluate(\n    (title) => {\n      const td = (window as any).__testData;\n      const event = [...td.events].find((e: any) => e.title === title);\n      if (!event) return false;\n      return td.getEventParticipants(event['@id']).some((p: any) => p.user === td.currentUserId);\n    },\n    eventTitle,\n  );\n  expect(found, `User should NOT appear in participants of \"${eventTitle}\"`).to.be.false;\n});",
    "lineNumber": 142
  },
  {
    "pattern": "l'inscription est idempotente pour l'événement {string}",
    "keyword": "Then",
    "file": "inscription.steps.ts",
    "sourceCode": "Then('l\\'inscription est idempotente pour l\\'événement {string}', async function (this: FestipodWorld, eventTitle: string) {\n  const count = await this.appFrame!.evaluate(\n    (title) => {\n      const td = (window as any).__testData;\n      const event = [...td.events].find((e: any) => e.title === title);\n      if (!event) return 0;\n      return td.getEventParticipants(event['@id']).filter((p: any) => p.user === td.currentUserId).length;\n    },\n    eventTitle,\n  );\n  expect(count, 'User should have exactly one participation record').to.equal(1);\n});",
    "lineNumber": 155
  },
  {
    "pattern": "je clique sur un événement",
    "keyword": "When",
    "file": "event.steps.ts",
    "sourceCode": "When('je clique sur un événement', async function (this: FestipodWorld) {\n  this.navigateTo('#/demo/event-detail');\n});",
    "lineNumber": 5
  },
  {
    "pattern": "je visualise l'événement {string}",
    "keyword": "Given",
    "file": "event.steps.ts",
    "sourceCode": "Given('je visualise l\\'événement {string}', async function (this: FestipodWorld, eventName: string) {\n  this.navigateTo('#/demo/event-detail');\n  expect(this.currentScreen, 'Event detail screen should be loaded').to.not.be.null;\n  this.attach(`Viewing event: ${eventName}`, 'text/plain');\n});",
    "lineNumber": 9
  },
  {
    "pattern": "je peux annuler et revenir à l'écran précédent",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('je peux annuler et revenir à l\\'écran précédent', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('create-event');\n  const source = this.getRenderedText();\n  const found = /onClick\\s*=\\s*\\{\\s*\\(\\)\\s*=>\\s*navigate\\s*\\(['\"]home['\"]\\)\\s*\\}[^>]*>✕</.test(source);\n  expect(found, 'Create event screen should have ✕ button with navigate(\"home\")').to.be.true;\n});",
    "lineNumber": 15
  },
  {
    "pattern": "je peux voir la liste des participants",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('je peux voir la liste des participants', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('event-detail');\n  const source = this.getRenderedText();\n  const hasAvatars = /<Avatar/.test(source);\n  const hasParticipantsSection = /Participants\\s*\\(\\d+\\)/.test(source);\n  expect(hasAvatars, 'Event detail should have Avatar components for participants').to.be.true;\n  expect(hasParticipantsSection, 'Event detail should have \"Participants (N)\" section').to.be.true;\n});",
    "lineNumber": 22
  },
  {
    "pattern": "je peux voir les détails de l'événement",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('je peux voir les détails de l\\'événement', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('event-detail');\n  const source = this.getRenderedText();\n  expect(/<Title[^>]*>[^<]+<\\/Title>/.test(source), 'Event detail should have a Title').to.be.true;\n  expect(/📅/.test(source), 'Event detail should have date emoji 📅').to.be.true;\n  expect(/🕓/.test(source), 'Event detail should have time emoji 🕓').to.be.true;\n  expect(/📍/.test(source), 'Event detail should have location emoji 📍').to.be.true;\n  expect(/À propos/.test(source), 'Event detail should have \"À propos\" section').to.be.true;\n});",
    "lineNumber": 31
  },
  {
    "pattern": "l'écran affiche les informations de l'événement",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('l\\'écran affiche les informations de l\\'événement', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('event-detail');\n  const source = this.getRenderedText();\n  expect(/<Title[^>]*>[^<]+<\\/Title>/.test(source), 'Event detail should have a Title').to.be.true;\n  expect(/📅/.test(source), 'Event detail should have date emoji 📅').to.be.true;\n  expect(/🕓/.test(source), 'Event detail should have time emoji 🕓').to.be.true;\n  expect(/📍/.test(source), 'Event detail should have location emoji 📍').to.be.true;\n  expect(/À propos/.test(source), 'Event detail should have \"À propos\" section').to.be.true;\n});",
    "lineNumber": 41
  },
  {
    "pattern": "je peux voir la liste des événements",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('je peux voir la liste des événements', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  if (this.currentScreenId === 'home') {\n    expect(/Mes événements à venir/.test(source), 'Home screen should have \"Événements à venir\" text').to.be.true;\n  } else if (this.currentScreenId === 'events') {\n    expect(/<Card[^>]*onClick/.test(source), 'Events screen should have clickable Card components').to.be.true;\n  } else {\n    expect.fail(`Unexpected screen \"${this.currentScreenId}\" - events list should be on home or events screen`);\n  }\n});",
    "lineNumber": 51
  },
  {
    "pattern": "les événements affichent leur lieu",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('les événements affichent leur lieu', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  const locationPattern = /📍.*<span[^>]*className=\"user-content\"[^>]*>[^<]+<\\/span>/;\n  expect(locationPattern.test(source), 'Event cards should display location text after 📍 emoji').to.be.true;\n});",
    "lineNumber": 62
  },
  {
    "pattern": "je peux m'inscrire à l'événement",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('je peux m\\'inscrire à l\\'événement', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('event-detail');\n  const source = this.getRenderedText();\n  const hasParticiperButton = /isJoined \\? '✓ Inscrit' : 'Participer'/.test(source);\n  expect(hasParticiperButton, 'Event detail should have Participer/Inscrit toggle button').to.be.true;\n});",
    "lineNumber": 68
  },
  {
    "pattern": "je peux me désinscrire de l'événement",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('je peux me désinscrire de l\\'événement', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('event-detail');\n  const source = this.getRenderedText();\n  const hasInscritButton = /isJoined \\? '✓ Inscrit' : 'Participer'/.test(source);\n  expect(hasInscritButton, 'Event detail should have Participer/Inscrit toggle button (click to unregister)').to.be.true;\n});",
    "lineNumber": 75
  },
  {
    "pattern": "le formulaire contient le champ obligatoire {string}",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('le formulaire contient le champ obligatoire {string}', async function (this: FestipodWorld, fieldName: string) {\n  expect(this.currentScreenId, 'This step is for form screens only').to.equal('create-event');\n  const source = this.getRenderedText();\n  const escapedName = fieldName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const pattern = new RegExp(`>${escapedName}\\\\s*\\\\*<`);\n  expect(pattern.test(source), `Field \"${fieldName}\" should be marked as required (with *) in create-event screen`).to.be.true;\n});",
    "lineNumber": 84
  },
  {
    "pattern": "le formulaire contient les champs obligatoires suivants:",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('le formulaire contient les champs obligatoires suivants:', async function (this: FestipodWorld, dataTable) {\n  expect(this.currentScreenId, 'This step is for form screens only').to.equal('create-event');\n  const source = this.getRenderedText();\n  const expectedFields = dataTable.raw().flat();\n  expectedFields.forEach((fieldName: string) => {\n    const escapedName = fieldName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n    const pattern = new RegExp(`>${escapedName}\\\\s*\\\\*<`);\n    expect(pattern.test(source), `Field \"${fieldName}\" should be marked as required (with *) in create-event screen`).to.be.true;\n  });",
    "lineNumber": 92
  },
  {
    "pattern": "le formulaire permet de détecter les doublons",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('le formulaire permet de détecter les doublons', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('create-event');\n  const source = this.getRenderedText();\n  expect(/showDuplicateWarning/.test(source), 'Form should have duplicate detection logic').to.be.true;\n  expect(/Événement similaire détecté/.test(source), 'Form should have duplicate warning message').to.be.true;\n});",
    "lineNumber": 103
  },
  {
    "pattern": "le formulaire permet d'importer depuis Mobilizon ou Transiscope",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('le formulaire permet d\\'importer depuis Mobilizon ou Transiscope', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('create-event');\n  const source = this.getRenderedText();\n  expect(/importableEvents/.test(source), 'Form should have importable events data').to.be.true;\n  expect(/Mobilizon/.test(source), 'Form should support Mobilizon import').to.be.true;\n  expect(/Transiscope/.test(source), 'Form should support Transiscope import').to.be.true;\n  expect(/Importer depuis une source externe/.test(source), 'Form should have import section').to.be.true;\n});",
    "lineNumber": 110
  },
  {
    "pattern": "l'import externe ne déclenche pas d'alerte doublon",
    "keyword": "Then",
    "file": "event.steps.ts",
    "sourceCode": "Then('l\\'import externe ne déclenche pas d\\'alerte doublon', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('create-event');\n  const source = this.getRenderedText();\n  expect(/importedFrom/.test(source), 'Form should track import source').to.be.true;\n  expect(/&& !importedFrom/.test(source), 'Duplicate warning should be disabled for imports').to.be.true;\n});",
    "lineNumber": 119
  },
  {
    "pattern": "je peux configurer mes notifications",
    "keyword": "Then",
    "file": "home.steps.ts",
    "sourceCode": "Then('je peux configurer mes notifications', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('settings');\n  const source = this.getRenderedText();\n  expect(/>Notifications</.test(source), 'Settings should have \"Notifications\" text').to.be.true;\n  expect(/<Toggle[^>]*checked=\\{notifications\\}/.test(source), 'Settings should have Toggle for notifications').to.be.true;\n});",
    "lineNumber": 5
  },
  {
    "pattern": "je clique sur un participant",
    "keyword": "When",
    "file": "user.steps.ts",
    "sourceCode": "When('je clique sur un participant', async function (this: FestipodWorld) {\n  this.navigateTo('#/demo/user-profile');\n});",
    "lineNumber": 5
  },
  {
    "pattern": "je visualise le profil de {string}",
    "keyword": "Given",
    "file": "user.steps.ts",
    "sourceCode": "Given('je visualise le profil de {string}', async function (this: FestipodWorld, userName: string) {\n  this.navigateTo('#/demo/user-profile');\n  expect(this.currentScreen, 'User profile screen should be loaded').to.not.be.null;\n  this.attach(`Viewing profile: ${userName}`, 'text/plain');\n});",
    "lineNumber": 9
  },
  {
    "pattern": "je peux voir mon profil",
    "keyword": "Then",
    "file": "user.steps.ts",
    "sourceCode": "Then('je peux voir mon profil', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('profile');\n  const source = this.getRenderedText();\n  expect(/<Avatar[^>]*initials=\"MD\"[^>]*size=\"lg\"/.test(source), 'Profile should have Avatar with initials=\"MD\" and size=\"lg\"').to.be.true;\n  expect(/<Title[^>]*>Marie Dupont<\\/Title>/.test(source), 'Profile should have Title \"Marie Dupont\"').to.be.true;\n  expect(/@mariedupont/.test(source), 'Profile should have username @mariedupont').to.be.true;\n});",
    "lineNumber": 15
  },
  {
    "pattern": "je peux voir le profil de l'utilisateur",
    "keyword": "Then",
    "file": "user.steps.ts",
    "sourceCode": "Then('je peux voir le profil de l\\'utilisateur', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('user-profile');\n  const source = this.getRenderedText();\n  expect(/<Avatar[^>]*initials=\"JD\"[^>]*size=\"lg\"/.test(source), 'User profile should have Avatar with initials=\"JD\" and size=\"lg\"').to.be.true;\n  expect(/<Title[^>]*>Jean Durand<\\/Title>/.test(source), 'User profile should have Title \"Jean Durand\"').to.be.true;\n  expect(/@jeandurand/.test(source), 'User profile should have username @jeandurand').to.be.true;\n});",
    "lineNumber": 23
  },
  {
    "pattern": "l'écran affiche les informations du profil",
    "keyword": "Then",
    "file": "user.steps.ts",
    "sourceCode": "Then('l\\'écran affiche les informations du profil', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  if (this.currentScreenId === 'profile') {\n    expect(/<Avatar[^>]*initials=\"MD\"/.test(source), 'Profile should have Avatar with initials=\"MD\"').to.be.true;\n    expect(/<Title[^>]*>Marie Dupont<\\/Title>/.test(source), 'Profile should have Title \"Marie Dupont\"').to.be.true;\n    expect(/@mariedupont/.test(source), 'Profile should have username @mariedupont').to.be.true;\n  } else if (this.currentScreenId === 'user-profile') {\n    expect(/<Avatar[^>]*initials=\"JD\"/.test(source), 'User profile should have Avatar with initials=\"JD\"').to.be.true;\n    expect(/<Title[^>]*>Jean Durand<\\/Title>/.test(source), 'User profile should have Title \"Jean Durand\"').to.be.true;\n    expect(/@jeandurand/.test(source), 'User profile should have username @jeandurand').to.be.true;\n  } else {\n    expect.fail(`Unexpected screen \"${this.currentScreenId}\" for profile info check`);\n  }\n});",
    "lineNumber": 31
  },
  {
    "pattern": "je peux contacter l'utilisateur",
    "keyword": "Then",
    "file": "user.steps.ts",
    "sourceCode": "Then('je peux contacter l\\'utilisateur', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('user-profile');\n  const source = this.getRenderedText();\n  const hasContactButton = /<Button>Contacter<\\/Button>/.test(source);\n  expect(hasContactButton, 'User profile should have \"Contacter\" button').to.be.true;\n});",
    "lineNumber": 46
  },
  {
    "pattern": "je peux voir les événements auxquels l'utilisateur a participé",
    "keyword": "Then",
    "file": "user.steps.ts",
    "sourceCode": "Then('je peux voir les événements auxquels l\\'utilisateur a participé', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('user-profile');\n  const source = this.getRenderedText();\n  expect(/Événements à venir/.test(source), 'User profile should have \"Événements à venir\" section').to.be.true;\n  expect(/Événements passés/.test(source), 'User profile should have \"Événements passés\" section').to.be.true;\n});",
    "lineNumber": 53
  },
  {
    "pattern": "les événements affichent leur localisation et distance",
    "keyword": "Then",
    "file": "user.steps.ts",
    "sourceCode": "Then('les événements affichent leur localisation et distance', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('user-profile');\n  const source = this.getRenderedText();\n  expect(/location: '[^']+'/.test(source), 'Events should have location data').to.be.true;\n  expect(/distance: \\d+/.test(source), 'Events should have distance data').to.be.true;\n  expect(/\\{event\\.location\\}/.test(source), 'Events should render location').to.be.true;\n  expect(/\\{event\\.distance\\}/.test(source), 'Events should render distance').to.be.true;\n});",
    "lineNumber": 60
  },
  {
    "pattern": "je peux voir le QR code",
    "keyword": "Then",
    "file": "user.steps.ts",
    "sourceCode": "Then('je peux voir le QR code', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  if (this.currentScreenId === 'share-profile') {\n    expect(/QR Code/.test(source), 'Share profile should have \"QR Code\" text').to.be.true;\n    expect(/Scannez pour me retrouver/.test(source), 'Share profile should have \"Scannez pour me retrouver\" text').to.be.true;\n  } else if (this.currentScreenId === 'meeting-points') {\n    expect(/Mon QR Code/.test(source), 'Meeting points should have \"Mon QR Code\" text').to.be.true;\n    expect(/Scannez pour m'ajouter/.test(source), 'Meeting points should have \"Scannez pour m\\'ajouter\" text').to.be.true;\n  } else {\n    expect.fail(`QR code should be on share-profile or meeting-points, not \"${this.currentScreenId}\"`);\n  }\n});",
    "lineNumber": 69
  },
  {
    "pattern": "je peux voir le lien de partage",
    "keyword": "Then",
    "file": "user.steps.ts",
    "sourceCode": "Then('je peux voir le lien de partage', async function (this: FestipodWorld) {\n  expect(this.currentScreenId, 'Share link should be on share-profile screen').to.equal('share-profile');\n  const source = this.getRenderedText();\n  expect(/Mon lien de profil/.test(source), 'Share profile should have \"Mon lien de profil\" text').to.be.true;\n  expect(/festipod\\.app\\/u\\//.test(source), 'Share profile should have profile link URL').to.be.true;\n});",
    "lineNumber": 82
  },
  {
    "pattern": "l'écran {string} est affiché",
    "keyword": "Given",
    "file": "form.steps.ts",
    "sourceCode": "Given('l\\'écran {string} est affiché', async function (this: FestipodWorld, screenName: string) {\n  const screenId = screenName.toLowerCase().replace(/ /g, '-');\n  this.navigateTo(`#/demo/${screenId}`);\n});",
    "lineNumber": 5
  },
  {
    "pattern": "le formulaire de création est vide",
    "keyword": "Given",
    "file": "form.steps.ts",
    "sourceCode": "Given('le formulaire de création est vide', async function (this: FestipodWorld) {\n  this.formFields.forEach((field, key) => {\n    this.formFields.set(key, { ...field, value: '' });",
    "lineNumber": 10
  },
  {
    "pattern": "le champ {string} est facultatif",
    "keyword": "Then",
    "file": "form.steps.ts",
    "sourceCode": "Then('le champ {string} est facultatif', async function (this: FestipodWorld, fieldName: string) {\n  const source = this.getRenderedText();\n  const escapedName = fieldName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const existsPattern = new RegExp(`>${escapedName}<`);\n  const requiredPattern = new RegExp(`>${escapedName}\\\\s*\\\\*<`);\n  expect(existsPattern.test(source), `Field \"${fieldName}\" should exist in screen`).to.be.true;\n  expect(requiredPattern.test(source), `Field \"${fieldName}\" should NOT be marked as required`).to.be.false;\n});",
    "lineNumber": 16
  },
  {
    "pattern": "le champ {string} est présent",
    "keyword": "Then",
    "file": "form.steps.ts",
    "sourceCode": "Then('le champ {string} est présent', async function (this: FestipodWorld, fieldName: string) {\n  const source = this.getRenderedText();\n  const escapedName = fieldName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const pattern = new RegExp(`>${escapedName}[^<]*<`);\n  expect(pattern.test(source), `Field \"${fieldName}\" should be present in screen`).to.be.true;\n});",
    "lineNumber": 25
  },
  {
    "pattern": "Scénario non implémenté",
    "keyword": "Given",
    "file": "navigation.steps.ts",
    "sourceCode": "Given('Scénario non implémenté', async function (this: FestipodWorld) {\n  return 'skipped';\n});",
    "lineNumber": 7
  },
  {
    "pattern": "je suis sur la page {string}",
    "keyword": "Given",
    "file": "navigation.steps.ts",
    "sourceCode": "Given('je suis sur la page {string}', async function (this: FestipodWorld, pageName: string) {\n  const screenId = resolveScreenId(pageName);\n  this.navigateTo(`#/demo/${screenId}`);\n});",
    "lineNumber": 38
  },
  {
    "pattern": "je suis connecté en tant qu'utilisateur",
    "keyword": "Given",
    "file": "navigation.steps.ts",
    "sourceCode": "Given('je suis connecté en tant qu\\'utilisateur', async function (this: FestipodWorld) {\n  this.isAuthenticated = true;\n});",
    "lineNumber": 43
  },
  {
    "pattern": "je suis connecté",
    "keyword": "Given",
    "file": "navigation.steps.ts",
    "sourceCode": "Given('je suis connecté', async function (this: FestipodWorld) {\n  this.isAuthenticated = true;\n});",
    "lineNumber": 47
  },
  {
    "pattern": "je ne suis pas connecté",
    "keyword": "Given",
    "file": "navigation.steps.ts",
    "sourceCode": "Given('je ne suis pas connecté', async function (this: FestipodWorld) {\n  this.isAuthenticated = false;\n});",
    "lineNumber": 51
  },
  {
    "pattern": "je navigue vers {string}",
    "keyword": "When",
    "file": "navigation.steps.ts",
    "sourceCode": "When('je navigue vers {string}', async function (this: FestipodWorld, pageName: string) {\n  const screenId = resolveScreenId(pageName);\n  this.navigateTo(`#/demo/${screenId}`);\n});",
    "lineNumber": 55
  },
  {
    "pattern": "je clique sur {string}",
    "keyword": "When",
    "file": "navigation.steps.ts",
    "sourceCode": "When('je clique sur {string}', async function (this: FestipodWorld, elementName: string) {\n  const source = this.getRenderedText();\n  const escapedName = elementName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const pattern = new RegExp(`onClick[^>]*>[^<]*${escapedName}`, 'i');\n  expect(pattern.test(source), `Clickable element \"${elementName}\" should exist in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 60
  },
  {
    "pattern": "je sélectionne {string}",
    "keyword": "When",
    "file": "navigation.steps.ts",
    "sourceCode": "When('je sélectionne {string}', async function (this: FestipodWorld, elementName: string) {\n  const source = this.getRenderedText();\n  const escapedName = elementName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const pattern = new RegExp(`onClick[^>]*>[^<]*${escapedName}`, 'i');\n  expect(pattern.test(source), `Selectable element \"${elementName}\" should exist in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 67
  },
  {
    "pattern": "je clique sur le bouton {string}",
    "keyword": "When",
    "file": "navigation.steps.ts",
    "sourceCode": "When('je clique sur le bouton {string}', async function (this: FestipodWorld, buttonName: string) {\n  const source = this.getRenderedText();\n  const escapedName = buttonName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const pattern = new RegExp(`<Button[^>]*>[^<]*${escapedName}[^<]*</Button>`, 'i');\n  expect(pattern.test(source), `Button \"${buttonName}\" should exist in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 74
  },
  {
    "pattern": "je suis redirigé vers {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('je suis redirigé vers {string}', async function (this: FestipodWorld, pageName: string) {\n  const screenId = resolveScreenId(pageName);\n  expect(this.currentScreenId).to.equal(screenId);\n});",
    "lineNumber": 81
  },
  {
    "pattern": "je vois l'écran {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('je vois l\\'écran {string}', async function (this: FestipodWorld, pageName: string) {\n  const screenId = resolveScreenId(pageName);\n  expect(this.currentScreenId).to.equal(screenId);\n});",
    "lineNumber": 86
  },
  {
    "pattern": "je reste sur la page {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('je reste sur la page {string}', async function (this: FestipodWorld, pageName: string) {\n  const screenId = resolveScreenId(pageName);\n  expect(this.currentScreenId).to.equal(screenId);\n});",
    "lineNumber": 91
  },
  {
    "pattern": "l'écran contient une section {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('l\\'écran contient une section {string}', async function (this: FestipodWorld, sectionName: string) {\n  expect(this.hasText(sectionName), `Section \"${sectionName}\" should be present in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 96
  },
  {
    "pattern": "je peux naviguer vers {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('je peux naviguer vers {string}', async function (this: FestipodWorld, pageName: string) {\n  const screenId = resolveScreenId(pageName);\n  const source = this.getRenderedText();\n  const pattern = new RegExp(`navigate\\\\s*\\\\(\\\\s*['\"]${screenId}['\"]\\\\s*\\\\)`);\n  expect(pattern.test(source), `Navigation to \"${screenId}\" should exist in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 100
  },
  {
    "pattern": "la navigation affiche {string} comme actif",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('la navigation affiche {string} comme actif', async function (this: FestipodWorld, menuItem: string) {\n  const source = this.getRenderedText();\n  const escapedItem = menuItem.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const pattern = new RegExp(`label:\\\\s*['\"]${escapedItem}['\"][^}]*active:\\\\s*true`, 'i');\n  expect(pattern.test(source), `Menu item \"${menuItem}\" should be active in NavBar of screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 107
  },
  {
    "pattern": "l'écran contient un bouton {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('l\\'écran contient un bouton {string}', async function (this: FestipodWorld, buttonText: string) {\n  expect(this.hasText(buttonText), `Button \"${buttonText}\" should be present in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 114
  },
  {
    "pattern": "l'écran contient un champ {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('l\\'écran contient un champ {string}', async function (this: FestipodWorld, fieldLabel: string) {\n  expect(this.hasText(fieldLabel), `Field \"${fieldLabel}\" should be present in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 118
  },
  {
    "pattern": "l'écran contient un texte {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('l\\'écran contient un texte {string}', async function (this: FestipodWorld, text: string) {\n  expect(this.hasText(text), `Text \"${text}\" should be present in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 122
  },
  {
    "pattern": "l'écran contient un avatar",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('l\\'écran contient un avatar', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  const hasAvatar = /<Avatar/.test(source);\n  expect(hasAvatar, `Avatar should be present in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 126
  },
  {
    "pattern": "je peux voir la section {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('je peux voir la section {string}', async function (this: FestipodWorld, sectionName: string) {\n  const source = this.getRenderedText();\n  const found = source.includes(sectionName);\n  if (!found) {\n    this.attach(`Looking for section: \"${sectionName}\"`, 'text/plain');\n    this.attach(`Rendered text: ${source.substring(0, 500)}...`, 'text/plain');\n  }\n  expect(found, `Section \"${sectionName}\" should be visible on screen`).to.be.true;\n});",
    "lineNumber": 132
  }
];

export function findStepDefinition(stepText: string): StepDefinitionInfo | null {
  for (const def of stepDefinitions) {
    // Convert Cucumber expression to regex
    // {string} -> "[^"]+"
    // {int} -> \\d+
    const regexPattern = def.pattern
      .replace(/\{string\}/g, '"[^"]+"')
      .replace(/\{int\}/g, '\\d+');

    try {
      const regex = new RegExp(regexPattern);
      if (regex.test(stepText)) {
        return def;
      }
    } catch {
      // If pattern fails, try simple includes
      const simplified = def.pattern.replace(/\{string\}/g, '').replace(/\{int\}/g, '').trim();
      if (stepText.includes(simplified)) {
        return def;
      }
    }
  }
  return null;
}
