// Auto-generated by scripts/extract-step-definitions.ts
// Do not edit manually - run "bun run steps:extract" to regenerate

export interface StepDefinitionInfo {
  pattern: string;
  keyword: 'Given' | 'When' | 'Then';
  file: string;
  sourceCode: string;
  lineNumber: number;
}

export const stepDefinitions: StepDefinitionInfo[] = [
  {
    "pattern": "Scénario non implémenté",
    "keyword": "Given",
    "file": "navigation.steps.ts",
    "sourceCode": "Given('Scénario non implémenté', async function (this: FestipodWorld) {\n  return 'skipped';\n});",
    "lineNumber": 7
  },
  {
    "pattern": "je suis sur la page {string}",
    "keyword": "Given",
    "file": "navigation.steps.ts",
    "sourceCode": "Given('je suis sur la page {string}', async function (this: FestipodWorld, pageName: string) {\n  const screenId = resolveScreenId(pageName);\n  this.navigateTo(`#/demo/${screenId}`);\n});",
    "lineNumber": 38
  },
  {
    "pattern": "je suis connecté en tant qu'utilisateur",
    "keyword": "Given",
    "file": "navigation.steps.ts",
    "sourceCode": "Given('je suis connecté en tant qu\\'utilisateur', async function (this: FestipodWorld) {\n  this.isAuthenticated = true;\n});",
    "lineNumber": 43
  },
  {
    "pattern": "je suis connecté",
    "keyword": "Given",
    "file": "navigation.steps.ts",
    "sourceCode": "Given('je suis connecté', async function (this: FestipodWorld) {\n  this.isAuthenticated = true;\n});",
    "lineNumber": 47
  },
  {
    "pattern": "je ne suis pas connecté",
    "keyword": "Given",
    "file": "navigation.steps.ts",
    "sourceCode": "Given('je ne suis pas connecté', async function (this: FestipodWorld) {\n  this.isAuthenticated = false;\n});",
    "lineNumber": 51
  },
  {
    "pattern": "je navigue vers {string}",
    "keyword": "When",
    "file": "navigation.steps.ts",
    "sourceCode": "When('je navigue vers {string}', async function (this: FestipodWorld, pageName: string) {\n  const screenId = resolveScreenId(pageName);\n  this.navigateTo(`#/demo/${screenId}`);\n});",
    "lineNumber": 55
  },
  {
    "pattern": "je clique sur {string}",
    "keyword": "When",
    "file": "navigation.steps.ts",
    "sourceCode": "When('je clique sur {string}', async function (this: FestipodWorld, elementName: string) {\n  const source = this.getRenderedText();\n  // Check that a clickable element with this text exists (onClick handler + text content)\n  const escapedName = elementName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const pattern = new RegExp(`onClick[^>]*>[^<]*${escapedName}`, 'i');\n  expect(pattern.test(source), `Clickable element \"${elementName}\" should exist in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 60
  },
  {
    "pattern": "je sélectionne {string}",
    "keyword": "When",
    "file": "navigation.steps.ts",
    "sourceCode": "When('je sélectionne {string}', async function (this: FestipodWorld, elementName: string) {\n  const source = this.getRenderedText();\n  // Check that a selectable element with this text exists\n  const escapedName = elementName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const pattern = new RegExp(`onClick[^>]*>[^<]*${escapedName}`, 'i');\n  expect(pattern.test(source), `Selectable element \"${elementName}\" should exist in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 68
  },
  {
    "pattern": "je clique sur le bouton {string}",
    "keyword": "When",
    "file": "navigation.steps.ts",
    "sourceCode": "When('je clique sur le bouton {string}', async function (this: FestipodWorld, buttonName: string) {\n  const source = this.getRenderedText();\n  // Check that a Button component with this label exists\n  const escapedName = buttonName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const pattern = new RegExp(`<Button[^>]*>[^<]*${escapedName}[^<]*</Button>`, 'i');\n  expect(pattern.test(source), `Button \"${buttonName}\" should exist in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 76
  },
  {
    "pattern": "je clique sur un participant",
    "keyword": "When",
    "file": "navigation.steps.ts",
    "sourceCode": "When('je clique sur un participant', async function (this: FestipodWorld) {\n  this.navigateTo('#/demo/user-profile');\n});",
    "lineNumber": 84
  },
  {
    "pattern": "je clique sur un événement",
    "keyword": "When",
    "file": "navigation.steps.ts",
    "sourceCode": "When('je clique sur un événement', async function (this: FestipodWorld) {\n  this.navigateTo('#/demo/event-detail');\n});",
    "lineNumber": 88
  },
  {
    "pattern": "je suis redirigé vers {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('je suis redirigé vers {string}', async function (this: FestipodWorld, pageName: string) {\n  const screenId = resolveScreenId(pageName);\n  expect(this.currentScreenId).to.equal(screenId);\n});",
    "lineNumber": 92
  },
  {
    "pattern": "je vois l'écran {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('je vois l\\'écran {string}', async function (this: FestipodWorld, pageName: string) {\n  const screenId = resolveScreenId(pageName);\n  expect(this.currentScreenId).to.equal(screenId);\n});",
    "lineNumber": 97
  },
  {
    "pattern": "je reste sur la page {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('je reste sur la page {string}', async function (this: FestipodWorld, pageName: string) {\n  const screenId = resolveScreenId(pageName);\n  expect(this.currentScreenId).to.equal(screenId);\n});",
    "lineNumber": 102
  },
  {
    "pattern": "l'écran contient une section {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('l\\'écran contient une section {string}', async function (this: FestipodWorld, sectionName: string) {\n  expect(this.hasText(sectionName), `Section \"${sectionName}\" should be present in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 107
  },
  {
    "pattern": "je peux annuler et revenir à l'écran précédent",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('je peux annuler et revenir à l\\'écran précédent', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('create-event');\n  const source = this.getRenderedText();\n  // Detect ✕ close button with onClick handler that calls navigate()\n  const found = /onClick\\s*=\\s*\\{\\s*\\(\\)\\s*=>\\s*navigate\\s*\\(['\"]home['\"]\\)\\s*\\}[^>]*>✕</.test(source);\n  expect(found, 'Create event screen should have ✕ button with navigate(\"home\")').to.be.true;\n});",
    "lineNumber": 111
  },
  {
    "pattern": "je peux naviguer vers {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('je peux naviguer vers {string}', async function (this: FestipodWorld, pageName: string) {\n  const screenId = resolveScreenId(pageName);\n  const source = this.getRenderedText();\n  // Check that a navigation link to this screen exists: navigate('screenId') or onClick={() => navigate('screenId')}\n  const pattern = new RegExp(`navigate\\\\s*\\\\(\\\\s*['\"]${screenId}['\"]\\\\s*\\\\)`);\n  expect(pattern.test(source), `Navigation to \"${screenId}\" should exist in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 119
  },
  {
    "pattern": "la navigation affiche {string} comme actif",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('la navigation affiche {string} comme actif', async function (this: FestipodWorld, menuItem: string) {\n  const source = this.getRenderedText();\n  // Check that NavBar has an item with this label and active: true\n  // Pattern: { icon: '...', label: 'menuItem', active: true }\n  const escapedItem = menuItem.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const pattern = new RegExp(`label:\\\\s*['\"]${escapedItem}['\"][^}]*active:\\\\s*true`, 'i');\n  expect(pattern.test(source), `Menu item \"${menuItem}\" should be active in NavBar of screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 127
  },
  {
    "pattern": "l'écran contient un bouton {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('l\\'écran contient un bouton {string}', async function (this: FestipodWorld, buttonText: string) {\n  expect(this.hasText(buttonText), `Button \"${buttonText}\" should be present in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 136
  },
  {
    "pattern": "l'écran contient un champ {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('l\\'écran contient un champ {string}', async function (this: FestipodWorld, fieldLabel: string) {\n  expect(this.hasText(fieldLabel), `Field \"${fieldLabel}\" should be present in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 140
  },
  {
    "pattern": "l'écran contient un texte {string}",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('l\\'écran contient un texte {string}', async function (this: FestipodWorld, text: string) {\n  expect(this.hasText(text), `Text \"${text}\" should be present in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 144
  },
  {
    "pattern": "l'écran contient un avatar",
    "keyword": "Then",
    "file": "navigation.steps.ts",
    "sourceCode": "Then('l\\'écran contient un avatar', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  const hasAvatar = /<Avatar/.test(source);\n  expect(hasAvatar, `Avatar should be present in screen \"${this.currentScreenId}\"`).to.be.true;\n});",
    "lineNumber": 148
  },
  {
    "pattern": "l'écran {string} est affiché",
    "keyword": "Given",
    "file": "form.steps.ts",
    "sourceCode": "Given('l\\'écran {string} est affiché', async function (this: FestipodWorld, screenName: string) {\n  const screenId = screenName.toLowerCase().replace(/ /g, '-');\n  this.navigateTo(`#/demo/${screenId}`);\n});",
    "lineNumber": 5
  },
  {
    "pattern": "le formulaire de création est vide",
    "keyword": "Given",
    "file": "form.steps.ts",
    "sourceCode": "Given('le formulaire de création est vide', async function (this: FestipodWorld) {\n  this.formFields.forEach((field, key) => {\n    this.formFields.set(key, { ...field, value: '' });",
    "lineNumber": 10
  },
  {
    "pattern": "le formulaire contient le champ obligatoire {string}",
    "keyword": "Then",
    "file": "form.steps.ts",
    "sourceCode": "Then('le formulaire contient le champ obligatoire {string}', async function (this: FestipodWorld, fieldName: string) {\n  // This step is for form screens only (create-event)\n  expect(this.currentScreenId, 'This step is for form screens only').to.equal('create-event');\n  const source = this.getRenderedText();\n  // CreateEventScreen.tsx: Required fields have \" *\" after label: >Label *<\n  const escapedName = fieldName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const pattern = new RegExp(`>${escapedName}\\\\s*\\\\*<`);\n  expect(pattern.test(source), `Field \"${fieldName}\" should be marked as required (with *) in create-event screen`).to.be.true;\n});",
    "lineNumber": 19
  },
  {
    "pattern": "le formulaire contient les champs obligatoires suivants:",
    "keyword": "Then",
    "file": "form.steps.ts",
    "sourceCode": "Then('le formulaire contient les champs obligatoires suivants:', async function (this: FestipodWorld, dataTable) {\n  // This step is for form screens only (create-event)\n  expect(this.currentScreenId, 'This step is for form screens only').to.equal('create-event');\n  const source = this.getRenderedText();\n  const expectedFields = dataTable.raw().flat();\n  expectedFields.forEach((fieldName: string) => {\n    // CreateEventScreen.tsx: Required fields have \" *\" after label: >Label *<\n    const escapedName = fieldName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n    const pattern = new RegExp(`>${escapedName}\\\\s*\\\\*<`);\n    expect(pattern.test(source), `Field \"${fieldName}\" should be marked as required (with *) in create-event screen`).to.be.true;\n  });",
    "lineNumber": 29
  },
  {
    "pattern": "le champ {string} est facultatif",
    "keyword": "Then",
    "file": "form.steps.ts",
    "sourceCode": "Then('le champ {string} est facultatif', async function (this: FestipodWorld, fieldName: string) {\n  const source = this.getRenderedText();\n  // Optional fields have label without \" *\": >Label< followed by Input\n  const escapedName = fieldName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  // Check field exists but NOT marked as required\n  const existsPattern = new RegExp(`>${escapedName}<`);\n  const requiredPattern = new RegExp(`>${escapedName}\\\\s*\\\\*<`);\n  expect(existsPattern.test(source), `Field \"${fieldName}\" should exist in screen`).to.be.true;\n  expect(requiredPattern.test(source), `Field \"${fieldName}\" should NOT be marked as required`).to.be.false;\n});",
    "lineNumber": 42
  },
  {
    "pattern": "le champ {string} est présent",
    "keyword": "Then",
    "file": "form.steps.ts",
    "sourceCode": "Then('le champ {string} est présent', async function (this: FestipodWorld, fieldName: string) {\n  const source = this.getRenderedText();\n  // Check that field label exists in screen source\n  const escapedName = fieldName.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\\\$&');\n  const pattern = new RegExp(`>${escapedName}[^<]*<`);\n  expect(pattern.test(source), `Field \"${fieldName}\" should be present in screen`).to.be.true;\n});",
    "lineNumber": 53
  },
  {
    "pattern": "je peux voir la liste des participants",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux voir la liste des participants', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('event-detail');\n  const source = this.getRenderedText();\n  // EventDetailScreen.tsx has: <Avatar components and \"Participants (12)\" text\n  const hasAvatars = /<Avatar/.test(source);\n  const hasParticipantsSection = /Participants\\s*\\(\\d+\\)/.test(source);\n  expect(hasAvatars, 'Event detail should have Avatar components for participants').to.be.true;\n  expect(hasParticipantsSection, 'Event detail should have \"Participants (N)\" section').to.be.true;\n});",
    "lineNumber": 5
  },
  {
    "pattern": "je peux voir les détails de l'événement",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux voir les détails de l\\'événement', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('event-detail');\n  const source = this.getRenderedText();\n  // EventDetailScreen.tsx has: <Title>, 📅, 🕓, 📍 emojis, and \"À propos\" section\n  expect(/<Title[^>]*>[^<]+<\\/Title>/.test(source), 'Event detail should have a Title').to.be.true;\n  expect(/📅/.test(source), 'Event detail should have date emoji 📅').to.be.true;\n  expect(/🕓/.test(source), 'Event detail should have time emoji 🕓').to.be.true;\n  expect(/📍/.test(source), 'Event detail should have location emoji 📍').to.be.true;\n  expect(/À propos/.test(source), 'Event detail should have \"À propos\" section').to.be.true;\n});",
    "lineNumber": 15
  },
  {
    "pattern": "je peux voir la section {string}",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux voir la section {string}', async function (this: FestipodWorld, sectionName: string) {\n  const source = this.getRenderedText();\n  // Detect section by text search\n  const found = source.includes(sectionName);\n  if (!found) {\n    this.attach(`Looking for section: \"${sectionName}\"`, 'text/plain');\n    this.attach(`Rendered text: ${source.substring(0, 500)}...`, 'text/plain');\n  }\n  expect(found, `Section \"${sectionName}\" should be visible on screen`).to.be.true;\n});",
    "lineNumber": 26
  },
  {
    "pattern": "je peux voir mon profil",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux voir mon profil', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('profile');\n  const source = this.getRenderedText();\n  // ProfileScreen.tsx has: <Avatar initials=\"MD\" size=\"lg\" />, <Title>Marie Dupont</Title>, @mariedupont\n  expect(/<Avatar[^>]*initials=\"MD\"[^>]*size=\"lg\"/.test(source), 'Profile should have Avatar with initials=\"MD\" and size=\"lg\"').to.be.true;\n  expect(/<Title[^>]*>Marie Dupont<\\/Title>/.test(source), 'Profile should have Title \"Marie Dupont\"').to.be.true;\n  expect(/@mariedupont/.test(source), 'Profile should have username @mariedupont').to.be.true;\n});",
    "lineNumber": 40
  },
  {
    "pattern": "je peux voir le profil de l'utilisateur",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux voir le profil de l\\'utilisateur', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('user-profile');\n  const source = this.getRenderedText();\n  // UserProfileScreen.tsx has: <Avatar initials=\"JD\" size=\"lg\" />, <Title>Jean Durand</Title>, @jeandurand\n  expect(/<Avatar[^>]*initials=\"JD\"[^>]*size=\"lg\"/.test(source), 'User profile should have Avatar with initials=\"JD\" and size=\"lg\"').to.be.true;\n  expect(/<Title[^>]*>Jean Durand<\\/Title>/.test(source), 'User profile should have Title \"Jean Durand\"').to.be.true;\n  expect(/@jeandurand/.test(source), 'User profile should have username @jeandurand').to.be.true;\n});",
    "lineNumber": 49
  },
  {
    "pattern": "je peux voir la liste des événements",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux voir la liste des événements', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  if (this.currentScreenId === 'home') {\n    // HomeScreen.tsx has: \"Événements à venir\" text and EventCard components\n    expect(/Mes événements à venir/.test(source), 'Home screen should have \"Événements à venir\" text').to.be.true;\n  } else if (this.currentScreenId === 'events') {\n    // EventsScreen.tsx has: EventCard components with event data\n    expect(/<Card[^>]*onClick/.test(source), 'Events screen should have clickable Card components').to.be.true;\n  } else {\n    expect.fail(`Unexpected screen \"${this.currentScreenId}\" - events list should be on home or events screen`);\n  }\n});",
    "lineNumber": 58
  },
  {
    "pattern": "les événements affichent leur lieu",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('les événements affichent leur lieu', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  // HomeScreen.tsx and EventsScreen.tsx EventCard components display location as:\n  // 📍 <span className=\"user-content\">{location}</span>\n  // Check that there's actual location text after the emoji\n  const locationPattern = /📍.*<span[^>]*className=\"user-content\"[^>]*>[^<]+<\\/span>/;\n  expect(locationPattern.test(source), 'Event cards should display location text after 📍 emoji').to.be.true;\n});",
    "lineNumber": 71
  },
  {
    "pattern": "je peux voir le QR code",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux voir le QR code', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  if (this.currentScreenId === 'share-profile') {\n    // ShareProfileScreen.tsx has: \"QR Code\" comment and \"Scannez pour me retrouver\" text\n    expect(/QR Code/.test(source), 'Share profile should have \"QR Code\" text').to.be.true;\n    expect(/Scannez pour me retrouver/.test(source), 'Share profile should have \"Scannez pour me retrouver\" text').to.be.true;\n  } else if (this.currentScreenId === 'meeting-points') {\n    // MeetingPointsScreen.tsx has: \"Mon QR Code\" text and \"Scannez pour m'ajouter\"\n    expect(/Mon QR Code/.test(source), 'Meeting points should have \"Mon QR Code\" text').to.be.true;\n    expect(/Scannez pour m'ajouter/.test(source), 'Meeting points should have \"Scannez pour m\\'ajouter\" text').to.be.true;\n  } else {\n    expect.fail(`QR code should be on share-profile or meeting-points, not \"${this.currentScreenId}\"`);\n  }\n});",
    "lineNumber": 80
  },
  {
    "pattern": "je peux voir le lien de partage",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux voir le lien de partage', async function (this: FestipodWorld) {\n  expect(this.currentScreenId, 'Share link should be on share-profile screen').to.equal('share-profile');\n  const source = this.getRenderedText();\n  // ShareProfileScreen.tsx has: \"Mon lien de profil\" text and profileLink variable\n  expect(/Mon lien de profil/.test(source), 'Share profile should have \"Mon lien de profil\" text').to.be.true;\n  expect(/festipod\\.app\\/u\\//.test(source), 'Share profile should have profile link URL').to.be.true;\n});",
    "lineNumber": 95
  },
  {
    "pattern": "je visualise l'événement {string}",
    "keyword": "Given",
    "file": "screen.steps.ts",
    "sourceCode": "Given('je visualise l\\'événement {string}', async function (this: FestipodWorld, eventName: string) {\n  this.navigateTo('#/demo/event-detail');\n  expect(this.currentScreen, 'Event detail screen should be loaded').to.not.be.null;\n  this.attach(`Viewing event: ${eventName}`, 'text/plain');\n});",
    "lineNumber": 106
  },
  {
    "pattern": "je visualise le profil de {string}",
    "keyword": "Given",
    "file": "screen.steps.ts",
    "sourceCode": "Given('je visualise le profil de {string}', async function (this: FestipodWorld, userName: string) {\n  this.navigateTo('#/demo/user-profile');\n  expect(this.currentScreen, 'User profile screen should be loaded').to.not.be.null;\n  this.attach(`Viewing profile: ${userName}`, 'text/plain');\n});",
    "lineNumber": 112
  },
  {
    "pattern": "l'écran affiche les informations de l'événement",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('l\\'écran affiche les informations de l\\'événement', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('event-detail');\n  const source = this.getRenderedText();\n  // EventDetailScreen.tsx has: <Title>, 📅, 🕓, 📍 emojis, and \"À propos\" section\n  expect(/<Title[^>]*>[^<]+<\\/Title>/.test(source), 'Event detail should have a Title').to.be.true;\n  expect(/📅/.test(source), 'Event detail should have date emoji 📅').to.be.true;\n  expect(/🕓/.test(source), 'Event detail should have time emoji 🕓').to.be.true;\n  expect(/📍/.test(source), 'Event detail should have location emoji 📍').to.be.true;\n  expect(/À propos/.test(source), 'Event detail should have \"À propos\" section').to.be.true;\n});",
    "lineNumber": 118
  },
  {
    "pattern": "l'écran affiche les informations du profil",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('l\\'écran affiche les informations du profil', async function (this: FestipodWorld) {\n  const source = this.getRenderedText();\n  if (this.currentScreenId === 'profile') {\n    // ProfileScreen.tsx has: <Avatar initials=\"MD\" size=\"lg\" />, <Title>Marie Dupont</Title>, @mariedupont\n    expect(/<Avatar[^>]*initials=\"MD\"/.test(source), 'Profile should have Avatar with initials=\"MD\"').to.be.true;\n    expect(/<Title[^>]*>Marie Dupont<\\/Title>/.test(source), 'Profile should have Title \"Marie Dupont\"').to.be.true;\n    expect(/@mariedupont/.test(source), 'Profile should have username @mariedupont').to.be.true;\n  } else if (this.currentScreenId === 'user-profile') {\n    // UserProfileScreen.tsx has: <Avatar initials=\"JD\" size=\"lg\" />, <Title>Jean Durand</Title>, @jeandurand\n    expect(/<Avatar[^>]*initials=\"JD\"/.test(source), 'User profile should have Avatar with initials=\"JD\"').to.be.true;\n    expect(/<Title[^>]*>Jean Durand<\\/Title>/.test(source), 'User profile should have Title \"Jean Durand\"').to.be.true;\n    expect(/@jeandurand/.test(source), 'User profile should have username @jeandurand').to.be.true;\n  } else {\n    expect.fail(`Unexpected screen \"${this.currentScreenId}\" for profile info check`);\n  }\n});",
    "lineNumber": 129
  },
  {
    "pattern": "je peux m'inscrire à l'événement",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux m\\'inscrire à l\\'événement', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('event-detail');\n  const source = this.getRenderedText();\n  // EventDetailScreen.tsx line 49: {isJoined ? '✓ Inscrit' : 'Participer'}\n  // The button shows \"Participer\" when not joined\n  const hasParticiperButton = /isJoined \\? '✓ Inscrit' : 'Participer'/.test(source);\n  expect(hasParticiperButton, 'Event detail should have Participer/Inscrit toggle button').to.be.true;\n});",
    "lineNumber": 149
  },
  {
    "pattern": "je peux me désinscrire de l'événement",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux me désinscrire de l\\'événement', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('event-detail');\n  const source = this.getRenderedText();\n  // EventDetailScreen.tsx line 49: {isJoined ? '✓ Inscrit' : 'Participer'}\n  // Same button toggles - clicking \"✓ Inscrit\" will unregister\n  const hasInscritButton = /isJoined \\? '✓ Inscrit' : 'Participer'/.test(source);\n  expect(hasInscritButton, 'Event detail should have Participer/Inscrit toggle button (click to unregister)').to.be.true;\n});",
    "lineNumber": 158
  },
  {
    "pattern": "je peux contacter l'utilisateur",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux contacter l\\'utilisateur', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('user-profile');\n  const source = this.getRenderedText();\n  // UserProfileScreen.tsx line 44: <Button>Contacter</Button>\n  const hasContactButton = /<Button>Contacter<\\/Button>/.test(source);\n  expect(hasContactButton, 'User profile should have \"Contacter\" button').to.be.true;\n});",
    "lineNumber": 167
  },
  {
    "pattern": "je peux voir les événements auxquels l'utilisateur a participé",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux voir les événements auxquels l\\'utilisateur a participé', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('user-profile');\n  const source = this.getRenderedText();\n  // UserProfileScreen.tsx line 52: \"Événements en commun\" section with pastEvents\n  expect(/Événements en commun/.test(source), 'User profile should have \"Événements en commun\" section').to.be.true;\n  expect(/pastEvents/.test(source), 'User profile should display pastEvents data').to.be.true;\n});",
    "lineNumber": 175
  },
  {
    "pattern": "je peux configurer mes notifications",
    "keyword": "Then",
    "file": "screen.steps.ts",
    "sourceCode": "Then('je peux configurer mes notifications', async function (this: FestipodWorld) {\n  expect(this.currentScreenId).to.equal('settings');\n  const source = this.getRenderedText();\n  // SettingsScreen.tsx line 25: <Text>Notifications</Text> with Toggle\n  expect(/>Notifications</.test(source), 'Settings should have \"Notifications\" text').to.be.true;\n  expect(/<Toggle[^>]*checked=\\{notifications\\}/.test(source), 'Settings should have Toggle for notifications').to.be.true;\n});",
    "lineNumber": 183
  }
];

export function findStepDefinition(stepText: string): StepDefinitionInfo | null {
  for (const def of stepDefinitions) {
    // Convert Cucumber expression to regex
    // {string} -> "[^"]+"
    // {int} -> \\d+
    const regexPattern = def.pattern
      .replace(/\{string\}/g, '"[^"]+"')
      .replace(/\{int\}/g, '\\d+');

    try {
      const regex = new RegExp(regexPattern);
      if (regex.test(stepText)) {
        return def;
      }
    } catch {
      // If pattern fails, try simple includes
      const simplified = def.pattern.replace(/\{string\}/g, '').replace(/\{int\}/g, '').trim();
      if (stepText.includes(simplified)) {
        return def;
      }
    }
  }
  return null;
}
